baseURL = "/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "OmniCAV"
[[menu.main]]
URL = "about"
name = "Project"
weight = 1
[[menu.main]]
URL = "contact"
name = "News"
weight = 4
[[menu.main]]
URL = "portfolio"
name = "FAQS"
weight = 3
[[menu.main]]
URL = "blog"
name = "Partners"
weight = 2
[params]
address = "UK"
author = "Johnathan Smith"
copyright = "Copyright &copy; 2020 OmniCAV. All rights reserved. Theme by [gethugothemes](https://gethugothemes.com)"
description = "This is meta description"
email = "example@omnicav.com"
google_analitycs_id = "Your ID"
home = "Home"
logo = "images/omnicav.png"
phone = "+00 000 00 0000"
theme_color = "#1d405e"
[params.contact]
enable = true
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "#"
icon = "ti-twitter-alt"
[[params.social]]
URL = "#"
icon = "ti-linkedin"